baseURL = "/"
languageCode = "en-us"
title = "|tʃəːp|"
theme = "kube"
description = "|tʃəːp|(chirp) is a free, open-source Twitter network collection and visualisation tool"
Paginate = 4

pygmentsCodeFences = true
pygmentsStyle = "friendly"

[Params]
  RSSLink = "/index.xml"
  author = "John Coene" # add your company name
  github = "JohnCoene" # add your github profile name
  twitter = "jdatap" # add your twitter profile
  email = "jcoenep@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = 1
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = 3
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = 2
    url = "/faq/"
